name: 'BicepDeploy with Azure CLI'

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:

  BicepDeployAzCLI:
    name: 'BicepDeploy with Azure CLI'
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: rg-bicep-samples
      ResourceGroupLocation: "japaneast"
    environment: production

    steps:

    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Bicep
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az deployment sub create --location 'JapanEast' --template-file main.bicep