name: 'BicepDeploy'

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:

  BicepDeploy:
    name: 'BicepDeploy'
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: rg-bicep-samples
      ResourceGroupLocation: "japaneast"
    environment: production

    steps:

    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Bicep Build
      run: |
        az bicep build --file ./main.bicep

    - name: Az CLI Create Resource Group
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}

    - name: Validate Azure Bicep
      uses: Azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.ResourceGroupName }}
        deploymentMode: Validate
        template: ./main.json
        deploymentName: ${{ env.ResourceGroupName }}

    - name: Deploy Azure Bicep
      uses: Azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.ResourceGroupName }}
        deploymentMode: Complete
        template: ./main.json
        deploymentName: ${{ env.ResourceGroupName }}